# Generated by Django 3.2 on 2021-04-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Programming Name')),
                ('code', models.PositiveIntegerField(blank=True, null=True, verbose_name='Code')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Student Name')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('programming_languages', models.ManyToManyField(to='student.ProgrammingLanguages')),
            ],
        ),
    ]
