# Generated by Django 3.2 on 2021-05-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_programming_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='programming_languages',
            field=models.ManyToManyField(blank=True, to='student.ProgrammingLanguages'),
        ),
    ]
