# Generated by Django 3.2 on 2021-05-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_programming_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='programming_languages',
        ),
        migrations.AddField(
            model_name='student',
            name='programming_languages',
            field=models.CharField(max_length=50, null=True, verbose_name='Programming Languages'),
        ),
    ]
